version: "3.9"

services:
  backend:
    image: python:3.11-slim
    container_name: imds-backend-dev
    working_dir: /app
    command: sh -c "pip install -r backend/requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app/backend
      - ./backend/app:/app/app
      - ./backend/data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8000/api/v1/health\")' || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5

  frontend:
    image: node:20-alpine
    container_name: imds-frontend-dev
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host"
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
